### ISSUE TITLE
Kernel build not possible

### ISSUE THREAD

**Issue by bju2000** [Azizb750/android_kernel_xiaomi_hermes#1]
Does the kernel build require a special tool chain?

**Comment by Azizb750** [comment]
hi there, sorry for late reply, you can compile it using either google toolchain or uber tc or sabermod or linaro.
just need to be aarch64-linux-android-
and gcc 4.9 version
you can compile using higher versions too but i dont recommend it

**Comment by bju2000** [comment]
Thank you for your answer. I made the 8.1 version with Google's main toolchain, so I tried to fix this and that, but I thought it was useless.

**Comment by Azizb750** [comment]
you need to patch the kernel to compile with higher (>5.0) gcc

**Comment by bju2000** [comment]
I have news. The same mt6755 Redmi Note 2/3 kernel has been revealed.

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/hennessy-l-oss

**Comment by Azizb750** [comment]
I know, if you see it I have even forked it

https://github.com/Azizb750/Xiaomi_Kernel_OpenSource/tree/hennessy-l-oss
